runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: main.app
- url: /img
  static_dir: img
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: "2.5.2"


